### ISSUE TITLE
How to join the task when task sets detached?

### ISSUE THREAD

**Issue by ethe** [stjepang/async-task#17]
`Task::detach` does not have a return, but `Task::set_detached` does, is it able to get the task output by `Task::detach`?

**Comment by taiki-e** [comment]
set_detached will only return a value if the task has already been completed.

I guess that it is probably preferable to use a (oneshot) channel and send the results, in your use case.

**Comment by ethe** [comment]
Thanks, I will try to use an approach of oneshot channel.
