### ISSUE TITLE
Option to avoid panicking when polling a cancelled task

### ISSUE THREAD

**Issue by mystor** [stjepang/async-task#20]
In `panic=abort` environments, currently polling a `Task` which was cancelled due to the `Runnable` being dropped will cause a panic and abort the entire panicking process. https://github.com/smol-rs/async-task/blob/f875ce8eda25e6a9a50ffdeb0201bed9f3596e61/src/task.rs#L368

It would be nice to have an alternative option for polling cancelled runnables which doesn't panic, either producing a `Result` or `Option` to indicate that the task was cancelled, or continuing to produce `poll::Pending` and cancelling the blocked task silently (e.g. by dropping the waker).

Exposing the `Task<T>::poll_task` method publicly should be sufficient to allow downstream crates to customize the behavior they want with wrappers, though `async_task` could also expose a wrapper type itself which delegates the `Future::poll` implementation directly to `poll_task` without the unwrap call.

**Comment by taiki-e** [comment]
I would accept a PR to add a fallible wrapper.

**Comment by mystor** [comment]
@taiki-e Would it be possible to cut a new release with this change? Would be slightly preferable to a pinned git revision.

**Comment by taiki-e** [comment]
Published in 4.1.0.
