### ISSUE TITLE
How can I clone a `Task`

### ISSUE THREAD

**Issue by raindust** [stjepang/async-task#26]
I want to create a `Task` object and retry it later if the `Task` failed. Is there any way I can do this?

**Comment by notgull** [comment]
I don't think so. While it is true that the inner raw `Task` is reference counted, it's only used to count the number of `Waker`s and `Runnable`s currently pointing to the task. There is no way to clone a `Task`.

What's your use case here? I feel like there is a more sensible way to do what you're trying to do.

**Comment by raindust** [comment]
I want to use https://github.com/smol-rs/async-executor in a WASM/WASI library that is a single-thread environment. Each of the async functions inside the library is finally called a `futures::channel::oneshot::Receiver` to try to get a value, and later there will be a call to the library interface that sends a value through `futures::channel::oneshot::Sender`.

It works well now if there is only one async function. But if there are nested async functions (which are actually wrapped into a single `Task`), we will use multiple `futures::channel::oneshot::Sender`s to send values multiple times. So far as I know, I can:
1. count the nested async functions manually and wait for all `Sender`s to send values, and meanwhile using the `Receiver`s block wait method (this is stupid and shall have no change to run if some `Sender`s do not send values)
2. try to run the `Task` each time if one of the `Sender`s want to send a value, use `Sender`s `try_recv` method and save the receiving value if the task is not complete, if there is an error then return directly.

If I use the second method, I should get a `Task` "copy", to rerun it later. 

So is there something I missed during the solution, or there is a better way to solve this?

**Comment by notgull** [comment]
Hmm, I might not be understanding this properly, but is there any reason why you can't use an MPSC channel instead of several cloned oneshot channels?

**Comment by raindust** [comment]
I use oneshot channels because I only need to receive a value once, these receivers are actually "reply callbacks with a UUID". I do not need to clone these oneshot channels because I can record received values (so I can get it later with UUID), what I what to clone is `Task` so that I can recall it later if failed

**Comment by notgull** [comment]
"Rerun a future if it failed" isn't the pattern for a `Task`. A `Task` is more of "pop a `Future` onto the heap so we can push it into a queue repeatedly and keep track of its state." Once the `Future` returns `Ready`, it's not meant to be restarted.

I would do one of two things here:

1). Just start a new task with the `Future` instead of cloning it.

2). Make your `Future`s more tolerant to failure. You said that this calls a UUID generator callback which can potentially fail? Try this:

```rust
loop {
    match generate_uuid().await {
        Ok(uuid) => {
            channel.send(uuid);
            break;
        }
        Err(e) => {
            log::error!("{:?}", e);
            // give other tasks a chance to run
            futures_lite::future::yield_now().await;
            continue;
        }
    }
}
```

**Comment by raindust** [comment]
I think `futures_lite::future::yield_now()` can work for me, thanks a lot
