### ISSUE TITLE
Why was metadata removed from a previous version of async-task?

### ISSUE THREAD

**Issue by notgull** [stjepang/async-task#38]
While I was browsing older commits for this crate, I noticed [this one](https://github.com/smol-rs/async-task/commit/42e3a6949f13e5582c03c1090d90a51c3ab82fd7), where the original author removed metadata. Recently, we merged #33, which added metadata to tasks. Why was metadata originally removed from tasks? If the reason is still salient for the current version of `async-task`, we may want to revert #33.

**Comment by taiki-e** [comment]
I don't know the context of that commit, but if I look at the examples changed in that commit, I see that the type aliases were defined every time. (also, there are a lot of "()" arguments) I guess such a lack of convenience of APIs is the motivation for that commit.

**Comment by notgull** [comment]
That makes sense. Our new version aliases the metadata to `()` by default, though, so we should be alright.
